package CalApp;


/**
* CalApp/calculatorOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from calculator.idl
* Sunday, September 11, 2016 12:05:38 PM IST
*/

public interface calculatorOperations 
{
  double addition (double x, double y);
  double subtraction (double x, double y);
  double multiplication (double x, double y);
  double division (double x, double y) throws CalApp.calculatorPackage.DivisionByZero;
  void shutdown ();
} // interface calculatorOperations
