package CalApp;


/**
* CalApp/calculatorHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from calculator.idl
*/

abstract public class calculatorHelper
{
  private static String  _id = "IDL:CalApp/calculator:1.0";

  public static void insert (org.omg.CORBA.Any a, CalApp.calculator that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static CalApp.calculator extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (CalApp.calculatorHelper.id (), "calculator");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static CalApp.calculator read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_calculatorStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, CalApp.calculator value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static CalApp.calculator narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof CalApp.calculator)
      return (CalApp.calculator)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      CalApp._calculatorStub stub = new CalApp._calculatorStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static CalApp.calculator unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof CalApp.calculator)
      return (CalApp.calculator)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      CalApp._calculatorStub stub = new CalApp._calculatorStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
