package CalApp;


/**
* CalApp/calculatorOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from calculator.idl
* lunes 27 de febrero de 2023 19H40' CET
*/

public interface calculatorOperations 
{
  double addition (double x, double y);
  double subtraction (double x, double y);
  double multiplication (double x, double y);
  double division (double x, double y) throws CalApp.calculatorPackage.DivisionByZero;
  double square_root (double x) throws CalApp.calculatorPackage.Negative;
  double squared (double x);
  void shutdown ();
} // interface calculatorOperations
