package CalApp;


/**
* CalApp/calculator.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from calculator.idl
* Sunday, September 11, 2016 12:05:38 PM IST
*/

public interface calculator extends calculatorOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface calculator
