package CalApp.calculatorPackage;


/**
* CalApp/calculatorPackage/Negative.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from calculator.idl
* miércoles 1 de marzo de 2023 18H26' CET
*/

public final class Negative extends org.omg.CORBA.UserException
{

  public Negative ()
  {
    super(NegativeHelper.id());
  } // ctor


  public Negative (String $reason)
  {
    super(NegativeHelper.id() + "  " + $reason);
  } // ctor

} // class Negative
